backend:
  name: git-gateway
  branch: main   # الفرع اللي عليه ملفات موقعك

media_folder: "public/uploads"   # مكان رفع الصور
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "content/site-ar.json"
        label: "Arabic Content"
        name: "site_ar"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "hero", widget: "text" }

      - file: "content/site-en.json"
        label: "English Content"
        name: "site_en"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "hero", widget: "text" }
